- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="
  
- name: Copy config file from NFS Share
  copy:
    src: /mnt/efs/config
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link


# copy helm installer from host.
- name: Copy file with owner and permissions
  ansible.posix.synchronize:
    src: ../resources/helm
    dest: ~{{ ansible_user }}/

- name: Install Helm. cd to helm & run script. Wont run if /usr/local/bin/helm exists
  become_user: root
  ansible.builtin.shell: ./helm_install.sh
  args:
    chdir: /home/{{ ansible_user }}/helm/
    creates: /usr/local/bin/helm
